name: ollama

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - .data:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.ollama.rule=Host(`ollama.abojaber.com`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls.certResolver=letsencrypt"
      - "traefik.http.routers.ollama-http.rule=Host(`ollama.abojaber.com`)"
      - "traefik.http.routers.ollama-http.entrypoints=web"
      - "traefik.http.routers.ollama-http.middlewares=ollama-redirect"
      - "traefik.http.middlewares.ollama-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: no
    networks:
      - ollama-network
      - traefik-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.chat.rule=Host(`chat.abojaber.com`)"
      - "traefik.http.routers.chat.entrypoints=websecure"
      - "traefik.http.routers.chat.tls.certResolver=letsencrypt"
      - "traefik.http.routers.chat.service=chat"
      - "traefik.http.routers.chat-http.rule=Host(`chat.abojaber.com`)"
      - "traefik.http.routers.chat-http.entrypoints=web"
      - "traefik.http.routers.chat-http.middlewares=chat-redirect"
      - "traefik.http.middlewares.chat-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-network
      - traefik-net

volumes:
  ollama:
  open-webui:

networks:
  ollama-network:
  traefik-net:
    external: true
    name: traefik-net
